/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SUN
 */
public class cWeather extends javax.swing.JFrame {

    /**
     * Creates new form cWeather
     */
    public cWeather() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        imgBack = new javax.swing.JLabel();
        txtINP = new javax.swing.JLabel();
        inP = new javax.swing.JTextField();
        day = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        day1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        day2 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        txtday2 = new javax.swing.JLabel();
        txtday1 = new javax.swing.JLabel();
        txtday = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tra cứu thời tiết");
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(null);

        txt.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setText("Tra cứu thời tiết");
        getContentPane().add(txt);
        txt.setBounds(790, 50, 480, 60);

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1c.png"))); // NOI18N
        getContentPane().add(img);
        img.setBounds(360, 0, 1190, 200);

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("Back");
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(90, 980, 160, 60);

        imgBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        getContentPane().add(imgBack);
        imgBack.setBounds(70, 980, 230, 60);

        txtINP.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtINP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtINP.setText("Nhập tỉnh/Thành phố:");
        txtINP.setToolTipText("");
        getContentPane().add(txtINP);
        txtINP.setBounds(200, 200, 430, 70);

        inP.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        inP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inPActionPerformed(evt);
            }
        });
        getContentPane().add(inP);
        inP.setBounds(630, 200, 750, 70);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        day.setViewportView(jTextArea1);

        getContentPane().add(day);
        day.setBounds(110, 450, 520, 510);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea2.setRows(5);
        day1.setViewportView(jTextArea2);

        getContentPane().add(day1);
        day1.setBounds(690, 450, 530, 510);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea3.setRows(5);
        day2.setViewportView(jTextArea3);

        getContentPane().add(day2);
        day2.setBounds(1280, 450, 530, 510);

        txtday2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtday2.setText("Ngày kia");
        getContentPane().add(txtday2);
        txtday2.setBounds(1470, 380, 200, 60);

        txtday1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtday1.setText("Ngày mai");
        getContentPane().add(txtday1);
        txtday1.setBounds(870, 380, 200, 60);

        txtday.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtday.setText("Hôm nay");
        getContentPane().add(txtday);
        txtday.setBounds(280, 380, 200, 60);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BG.png"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, 0, 2140, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        UI u=new UI();
        u.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void inPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cWeather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cWeather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cWeather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cWeather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cWeather().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton back;
    private javax.swing.JScrollPane day;
    private javax.swing.JScrollPane day1;
    private javax.swing.JScrollPane day2;
    private javax.swing.JLabel img;
    private javax.swing.JLabel imgBack;
    private javax.swing.JTextField inP;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txtINP;
    private javax.swing.JLabel txtday;
    private javax.swing.JLabel txtday1;
    private javax.swing.JLabel txtday2;
    // End of variables declaration//GEN-END:variables
}
